/* Generated By:JavaCC: Do not edit this line. LexicoConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SUM = 1;
  /** RegularExpression Id. */
  int SUB = 2;
  /** RegularExpression Id. */
  int MULT = 3;
  /** RegularExpression Id. */
  int PAREOP = 4;
  /** RegularExpression Id. */
  int PARECL = 5;
  /** RegularExpression Id. */
  int NUMENT = 6;
  /** RegularExpression Id. */
  int EPSILON = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SUM>",
    "<SUB>",
    "<MULT>",
    "<PAREOP>",
    "<PARECL>",
    "<NUMENT>",
    "\"\"",
    "<token of kind 8>",
    "<token of kind 9>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
