/* Generated By:JavaCC: Do not edit this line. LexicoConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 1;
  /** RegularExpression Id. */
  int INT = 2;
  /** RegularExpression Id. */
  int FLOAT = 3;
  /** RegularExpression Id. */
  int CHAR = 4;
  /** RegularExpression Id. */
  int RETURN = 5;
  /** RegularExpression Id. */
  int VOID = 6;
  /** RegularExpression Id. */
  int ELSE = 7;
  /** RegularExpression Id. */
  int WHILE = 8;
  /** RegularExpression Id. */
  int INPUT = 9;
  /** RegularExpression Id. */
  int OUTPUT = 10;
  /** RegularExpression Id. */
  int SUM = 11;
  /** RegularExpression Id. */
  int SUB = 12;
  /** RegularExpression Id. */
  int MULT = 13;
  /** RegularExpression Id. */
  int DIV = 14;
  /** RegularExpression Id. */
  int MOD = 15;
  /** RegularExpression Id. */
  int BRACKETOPEN = 16;
  /** RegularExpression Id. */
  int BRACKETCLOSE = 17;
  /** RegularExpression Id. */
  int SQUAREBRACKETOPEN = 18;
  /** RegularExpression Id. */
  int SQUAREBRACKETCLOSE = 19;
  /** RegularExpression Id. */
  int CURLYBRACKETOPEN = 20;
  /** RegularExpression Id. */
  int CURLYBRACKETCLOSE = 21;
  /** RegularExpression Id. */
  int LESSEQUAL = 22;
  /** RegularExpression Id. */
  int MOREEQUAL = 23;
  /** RegularExpression Id. */
  int EQUALS = 24;
  /** RegularExpression Id. */
  int NOTEQUALS = 25;
  /** RegularExpression Id. */
  int ANGLEBRACKETOPEN = 26;
  /** RegularExpression Id. */
  int ANGLEBRACKETCLOSE = 27;
  /** RegularExpression Id. */
  int EQUIVALENCE = 28;
  /** RegularExpression Id. */
  int SEMICOLON = 29;
  /** RegularExpression Id. */
  int COMMA = 30;
  /** RegularExpression Id. */
  int ID = 31;
  /** RegularExpression Id. */
  int NUMENT = 32;
  /** RegularExpression Id. */
  int NUMREAL = 33;
  /** RegularExpression Id. */
  int SIMPLECHAR = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"if\"",
    "\"int\"",
    "\"float\"",
    "\"char\"",
    "\"return\"",
    "\"void\"",
    "\"else\"",
    "\"while\"",
    "\"input\"",
    "\"output\"",
    "<SUM>",
    "<SUB>",
    "<MULT>",
    "<DIV>",
    "<MOD>",
    "<BRACKETOPEN>",
    "<BRACKETCLOSE>",
    "<SQUAREBRACKETOPEN>",
    "<SQUAREBRACKETCLOSE>",
    "<CURLYBRACKETOPEN>",
    "<CURLYBRACKETCLOSE>",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "<ANGLEBRACKETOPEN>",
    "<ANGLEBRACKETCLOSE>",
    "<EQUIVALENCE>",
    "<SEMICOLON>",
    "<COMMA>",
    "<ID>",
    "<NUMENT>",
    "<NUMREAL>",
    "<SIMPLECHAR>",
    "<token of kind 35>",
    "<token of kind 36>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 41>",
    "<token of kind 42>",
    "<token of kind 43>",
    "<token of kind 44>",
    "<token of kind 45>",
  };

}
